
FROM node:18
WORKDIR /app
# all package must be install in container. Don't install your package locally 
COPY package*.json ./
RUN npm install && npm install -g @nestjs/cli
COPY . .
RUN npx prisma generate 
EXPOSE ${NEST_RUNNING_PORT}
CMD ["npm", "run", "start:dev"]


