
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install && npm install -g @nestjs/cli
COPY . .
# RUN npx prisma validate 
# RUN npx prisma generate 
EXPOSE ${NEST_RUNNING_PORT}
CMD ["npm", "run", "start:dev"]


